version: '3.8'
services:
  producttracking-backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - producttracking-db
  producttracking-db:
    image: postgres:16
    container_name: producttracking-db
    environment:
      POSTGRES_DB: product_tracking
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "listen_addresses=*"]
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"