apiVersion: v1
kind: Service
metadata:
  name: producttracking-backend
  namespace: product-tracking
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: producttracking-backend