apiVersion: apps/v1
kind: Deployment
metadata:
  name: producttracking-backend
  namespace: product-tracking
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producttracking-backend
  template:
    metadata:
      labels:
        app: producttracking-backend
    spec:
      containers:
        - name: backend
          image: your-backend-image:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql-headless:5432/product_tracking"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password