apiVersion: v1
kind: Service
metadata:
  name: producttracking-backend
spec:
  type: NodePort
  selector:
    app: producttracking-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
