apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-producttracking-db-new
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath
  volumeName: postgres-pv