apiVersion: v1
kind: Service
metadata:
  name: producttracking-backend
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: producttracking-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080