apiVersion: apps/v1
kind: Deployment
metadata:
  name: producttracking-backend
  namespace: default  # Eğer özel namespace kullanıyorsan değiştir
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producttracking-backend
  template:
    metadata:
      labels:
        app: producttracking-backend
    spec:
      containers:
        - name: backend
          image: producttracking-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://producttracking-db.default.svc.cluster.local:5432/product_tracking"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          resources:
            limits:
              memory: "500Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---