apiVersion: v1
kind: Service
metadata:
  name: producttracking-db-primary
  namespace: default
spec:
  selector:
    cluster-name: producttracking-db
    spilo-role: master  # Patroni'de Primary olan node "master" olarak gözüküyor.
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432